# Generated by Django 5.2.10 on 2026-01-10 12:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='اسم الوسيط')),
                ('telephone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('organisation', models.CharField(blank=True, max_length=255, verbose_name='الجهة / المؤسسة')),
            ],
            options={
                'verbose_name': 'وسيط',
                'verbose_name_plural': 'الوسطاء',
            },
        ),
        migrations.CreateModel(
            name='Orphelin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='رقم اليتيم')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('nni', models.CharField(max_length=20, unique=True, verbose_name='الرقم الوطني للتعريف')),
                ('genre', models.CharField(choices=[('m', 'ذكر'), ('f', 'أنثى')], max_length=1, verbose_name='الجنس')),
                ('date_naissance', models.DateField(verbose_name='تاريخ الميلاد')),
                ('nom_tuteur', models.CharField(max_length=255, verbose_name='اسم الولي')),
                ('telephone_tuteur', models.CharField(max_length=20, verbose_name='هاتف الولي')),
                ('adresse', models.TextField(verbose_name='العنوان')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول')),
                ('scolarite', models.CharField(choices=[('non_scolarise', 'غير متمدرس'), ('hors_age', 'دون سن الدراسة'), ('scolarise', 'متمدرس')], max_length=20, verbose_name='حالة التمدرس')),
                ('niveau_scolaire', models.CharField(blank=True, max_length=100, verbose_name='المستوى الدراسي')),
                ('etat_sante', models.TextField(blank=True, verbose_name='الحالة الصحية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='orphelins/photos/', verbose_name='صورة اليتيم')),
                ('dossier_pdf', models.FileField(blank=True, null=True, upload_to='orphelins/dossiers/', verbose_name='ملف اليتيم (PDF)')),
                ('statut', models.CharField(choices=[('actif', 'نشط'), ('suspendu', 'موقوف'), ('archive', 'مؤرشف')], default='actif', max_length=20, verbose_name='وضعية اليتيم')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
            ],
            options={
                'verbose_name': 'يتيم',
                'verbose_name_plural': 'الأيتام',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='اسم الكافل')),
                ('type_sponsor', models.CharField(choices=[('individuel', 'فرد'), ('organisation', 'مؤسسة')], max_length=20, verbose_name='نوع الكافل')),
                ('nationalite', models.CharField(blank=True, max_length=100, verbose_name='الجنسية')),
                ('telephone', models.CharField(max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('adresse', models.TextField(blank=True, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'كافل',
                'verbose_name_plural': 'الكافلون',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'مدير عام'), ('accountant', 'محاسب'), ('staff', 'موظف'), ('field', 'مشرف ميداني')], max_length=20, verbose_name='الدور')),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('groups', models.ManyToManyField(blank=True, related_name='core_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='core_users_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'مستخدم',
                'verbose_name_plural': 'المستخدمون',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('modele', models.CharField(max_length=100, verbose_name='النموذج')),
                ('objet_id', models.CharField(max_length=50, verbose_name='المعرف')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل التدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
            },
        ),
        migrations.CreateModel(
            name='Parrainage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_kafala', models.CharField(choices=[('interne', 'داخلية'), ('externe', 'خارجية')], max_length=20, verbose_name='جهة الكفالة')),
                ('montant_mru', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='مبلغ الكفالة بالأوقية')),
                ('montant_devise', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ بالعملة الأجنبية')),
                ('devise', models.CharField(blank=True, max_length=10, verbose_name='العملة')),
                ('solde', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الرصيد')),
                ('date_debut', models.DateField(verbose_name='تاريخ بداية الكفالة')),
                ('date_fin', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية الكفالة')),
                ('statut', models.CharField(choices=[('active', 'سارية'), ('terminee', 'منتهية'), ('suspendue', 'معلقة')], default='active', max_length=20, verbose_name='الحالة')),
                ('intermediaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.intermediaire', verbose_name='الوسيط')),
                ('orphelin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.orphelin', verbose_name='اليتيم')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sponsor', verbose_name='الكافل')),
            ],
            options={
                'verbose_name': 'كفالة',
                'verbose_name_plural': 'الكفالات',
                'unique_together': {('orphelin', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='TransactionFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_transaction', models.CharField(choices=[('entree', 'دخل'), ('sortie', 'صرف')], max_length=10, verbose_name='نوع العملية')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ العملية')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئت بواسطة')),
                ('parrainage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parrainage', verbose_name='الكفالة')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
            },
        ),
    ]
