# Generated by Django 5.2.10 on 2026-01-11 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orphelin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='dossier_pdf',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='orphelins/dossiers/', verbose_name='ملف اليتيم (PDF)'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='photo',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='orphelins/photos/', verbose_name='صورة اليتيم'),
        ),
    ]
