# Generated by Django 5.2.10 on 2026-01-11 04:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_orphelin_dossier_pdf_alter_orphelin_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='dossier_pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='dossier'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo'),
        ),
    ]
