# Generated by Django 5.2.10 on 2026-01-14 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_orphelin_dossier_pdf_alter_orphelin_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orphelin',
            name='annee_deces_pere',
            field=models.IntegerField(blank=True, null=True, verbose_name='سنة وفاة الأب'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='cause_deces_pere',
            field=models.CharField(blank=True, max_length=255, verbose_name='سبب وفاة الأب'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='classe',
            field=models.CharField(blank=True, max_length=50, verbose_name='الفصل الدراسي'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='cree_par',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphelins_crees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='etat_logement',
            field=models.CharField(blank=True, max_length=255, verbose_name='حالة السكن'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='etat_mere',
            field=models.CharField(blank=True, choices=[('veuve', 'أرملة'), ('remariee', 'متزوجة')], max_length=20, verbose_name='حالة الأم'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='lien_maps',
            field=models.URLField(blank=True, null=True, verbose_name='رابط الموقع (Maps)'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='nature_orphelin',
            field=models.CharField(blank=True, choices=[('pere', 'فقد الأب'), ('parents', 'فقد الأبوين')], max_length=10, verbose_name='طبيعة اليتم'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='niveau_social',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('tres_bon', 'جيد جدا'), ('bon', 'جيد'), ('moyen', 'متوسط'), ('faible', 'ضعيف'), ('tres_faible', 'ضعيف جدا')], max_length=20, verbose_name='المستوى الاجتماعي'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='nom_ecole',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم المدرسة'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=255, verbose_name='اسم الأم'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='nombre_freres',
            field=models.IntegerField(default=0, verbose_name='عدد الإخوة'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='rang_entre_freres',
            field=models.IntegerField(default=1, verbose_name='ترتيبه بين الإخوة'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='statut_verification',
            field=models.CharField(choices=[('en_attente', 'في انتظار التدقيق'), ('valide', 'مفعل'), ('rejete', 'مرفوض')], default='en_attente', max_length=20, verbose_name='حالة التدقيق'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='taille_famille',
            field=models.IntegerField(default=1, verbose_name='عدد أفراد الأسرة'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='travail_pere',
            field=models.CharField(blank=True, max_length=255, verbose_name='عمل الأب قبل الوفاة'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='travail_tuteur',
            field=models.CharField(blank=True, max_length=255, verbose_name='عمل الوصي'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='type_logement',
            field=models.CharField(blank=True, choices=[('maison', 'منزل'), ('arich', 'عريش'), ('banco', 'بيت من الطين'), ('baraque', 'براكة')], max_length=20, verbose_name='نوع السكن'),
        ),
        migrations.AddField(
            model_name='orphelin',
            name='verifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orphelins_verifies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم اليتيم'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='etat_sante',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('tres_bon', 'جيد جدا'), ('bon', 'جيد'), ('moyen', 'متوسط'), ('faible', 'ضعيف'), ('tres_faible', 'ضعيف جدا')], max_length=20, verbose_name='المستوى الصحي'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='niveau_scolaire',
            field=models.CharField(blank=True, choices=[('excellent', 'ممتاز'), ('tres_bon', 'جيد جدا'), ('bon', 'جيد'), ('moyen', 'متوسط'), ('faible', 'ضعيف'), ('tres_faible', 'ضعيف جدا')], max_length=20, verbose_name='المستوى الدراسي'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='scolarite',
            field=models.CharField(choices=[('non_scolarise', 'غير متمدرس'), ('hors_age', 'دون سن الدراسة'), ('scolarise', 'متمدرس'), ('mahdari', 'محضري')], max_length=20, verbose_name='حالة التمدرس'),
        ),
        migrations.AlterField(
            model_name='orphelin',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('suspendu', 'موقوف'), ('archive', 'مؤرشف'), ('eligible', 'مرشح للكفالة')], default='actif', max_length=20, verbose_name='وضعية اليتيم'),
        ),
    ]
