# Generated by Django 5.2.10 on 2026-01-15 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orphelin_annee_deces_pere_orphelin_cause_deces_pere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainage',
            name='montant_mois',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المصروف الشهري بالأوقية'),
        ),
    ]
