# Generated by Django 5.2.10 on 2026-01-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_parrainage_montant_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainage',
            name='montant_devise_mois',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ الشهري بالعملة الأجنبية'),
        ),
    ]
