# Generated by Django 5.2.10 on 2026-01-15 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parrainage_montant_devise_mois'),
    ]

    operations = [
        migrations.AddField(
            model_name='parrainage',
            name='duree',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='مدة الكفالة'),
        ),
    ]
