# Generated by Django 5.2.10 on 2026-01-16 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_parrainage_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfinanciere',
            name='montant_devise',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='المبلغ بالعملة الأجنبية'),
        ),
    ]
