# Generated by Django 5.2.10 on 2026-01-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transactionfinanciere_montant_devise'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionfinanciere',
            name='annee',
            field=models.IntegerField(blank=True, null=True, verbose_name='السنة'),
        ),
        migrations.AddField(
            model_name='transactionfinanciere',
            name='mois',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], null=True, verbose_name='الشهر'),
        ),
    ]
