# Generated by Django 5.2.10 on 2026-01-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_transactionfinanciere_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orphelin',
            name='statut',
            field=models.CharField(choices=[('actif', 'نشط'), ('suspendu', 'موقوف'), ('archive', 'مؤرشف'), ('eligible', 'مرشح للكفالة')], default='eligible', max_length=20, verbose_name='وضعية اليتيم'),
        ),
    ]
