# """
# Django settings for tadamunproject project.

# Generated by 'django-admin startproject' using Django 5.2.1.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.2/ref/settings/
# """

# from pathlib import Path

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
# import dj_database_url
# import os


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-i*9@i)4jfn!roc)kmxf)z%iqhp^i#=9!nq8+f2yooioxm$y@mw'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = False

# ALLOWED_HOSTS = ['*']


# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'cloudinary_storage' , 
#     'cloudinary' , 
#     'crispy_forms',
#     'crispy_bootstrap5',

#     'core',
# ]

# # INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']

# # CLOUDINARY_STORAGE = {
# #     'CLOUD_NAME': 'ddffza3q3',
# #     'API_KEY': '597189217612215',
# #     'API_SECRET': 'WFgU9-gkBE9Q0NP9k57nmyDpJU0',
# # }

# # DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]

# # STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ROOT_URLCONF = 'tadamunproject.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / 'templates'], 
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'tadamunproject.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }

# # prod
# # DATABASES = {'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'))}

# # localhost
# DATABASES = {
#     'default': dj_database_url.config(
#         default="postgresql://tadamuon_db:bioaty29BSdXevhxi2VzBqrul3F7uiqb@dpg-d5hdmtumcj7s73avits0-a.virginia-postgres.render.com/tadamuon_db"
#     )
# }

# # Password validation
# # https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'

# USE_I18N = True

# USE_TZ = True


# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.2/howto/static-files/

# # STATIC_URL = 'static/'

# # Default primary key field type
# # https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# AUTH_USER_MODEL = 'core.User'

# # MEDIA_URL = '/media/'
# # MEDIA_ROOT = BASE_DIR / 'media'

# CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
# CRISPY_TEMPLATE_PACK = "bootstrap5"

# LOGIN_REDIRECT_URL = '/'

# LOGOUT_REDIRECT_URL = '/login/'

# LOGIN_URL = '/login/'



# # INSTALLED_APPS += ['cloudinary', 'cloudinary_storage']

# CLOUDINARY_STORAGE = {
#     'CLOUD_NAME': 'ddffza3q3',
#     'API_KEY': '597189217612215',
#     'API_SECRET': 'WFgU9-gkBE9Q0NP9k57nmyDpJU0',
# }

# DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'

# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'

# STATICFILES_STORAGE  =  'cloudinary_storage.storage.StaticHashedCloudinaryStorage'

# =============
from pathlib import Path
import os
import dj_database_url

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-i*9@i)4jfn!roc)kmxf)z%iqhp^i#=9!nq8+f2yooioxm$y@mw'

DEBUG = False

ALLOWED_HOSTS = ['*']

# ==========================
# APPLICATIONS
# ==========================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Cloudinary (MEDIA uniquement)
    'cloudinary',
    'cloudinary_storage',

    # UI
    'crispy_forms',
    'crispy_bootstrap5',

    # App
    'core',
]

# ==========================
# MIDDLEWARE
# ==========================

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # STATIC
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tadamunproject.urls'

# ==========================
# TEMPLATES
# ==========================

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tadamunproject.wsgi.application'

# ==========================
# DATABASE
# ==========================++++

# DATABASES = {
#     'default': dj_database_url.config(
#         default="postgresql://tadamuon_db:bioaty29BSdXevhxi2VzBqrul3F7uiqb@dpg-d5hdmtumcj7s73avits0-a.virginia-postgres.render.com/tadamuon_db",
#         conn_max_age=600,
#         ssl_require=True
#     )
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ==========================
# AUTH
# ==========================

AUTH_USER_MODEL = 'core.User'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# ==========================
# STATIC FILES (CSS / JS)
# ==========================

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# ==========================
# CLOUDINARY (MEDIA FILES)
# ==========================

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'ddffza3q3',
    'API_KEY': '597189217612215',
    'API_SECRET': 'WFgU9-gkBE9Q0NP9k57nmyDpJU0',
}

import cloudinary
import cloudinary.uploader
import cloudinary.api

cloudinary.config(
    cloud_name="ddffza3q3",
    api_key="597189217612215",
    api_secret="WFgU9-gkBE9Q0NP9k57nmyDpJU0",
    secure=True
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'

# ❌ PAS DE MEDIA_URL
# ❌ PAS DE MEDIA_ROOT

# ==========================
# CRISPY
# ==========================

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
